name: acc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  firebase_crashlytics: "^2.2.2"

  provider: ^5.0.0
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.2.0
  http: ^0.13.3
  crypto: ^3.0.1
  shared_preferences: ^2.0.6
  # For OTP text field
  pin_code_fields: ^7.2.0
  # Captcha
  ps_code_checking: ^0.0.3
  encrypt: ^5.0.0
  json_annotation: ^3.1.0
  image_picker: ^0.8.1+3
  scrollable_positioned_list: ^0.1.10
  path_provider: any
  dropdown_search: ^0.6.3
  file_picker: ^3.0.3
  webview_flutter: ^2.0.12
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0
  local_auth: ^1.1.6
  cached_network_image: ^3.1.0
  flutter_tindercard: ^0.2.0
  url_launcher: ^6.0.9
  advance_pdf_viewer: ^2.0.0
  chips_choice: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/company_logo/app_logo_vertical.png"
  # For Android only
  # image_path_android
  # For iOS only
  # image_path_ios

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/dashboard/
    - assets/images/investor/
    - assets/images/navigation/
    - assets/images/social_media/
    - assets/images/company_logo/
    - assets/images/dummy/
    - assets/images/UserProfile.png
    - assets/images/company_logo/
    - assets/images/user_type/
    - assets/amicorp.json
    - assets/images/fundraiser/
    - assets/images/investor/found_us/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Medium.otf
          weight: 500

  #- family: Poppins
  # fonts:
  #   - asset: assets/fonts/Poppins-ExtraLight.ttf
  #   - asset: assets/fonts/Poppins-Light.ttf
  #   - asset: assets/fonts/Poppins-Medium.ttf
  #   - asset: assets/fonts/Poppins-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
